/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author giovanni
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnAgregarFoto = new javax.swing.JMenuItem();
        mnEliminarFoto = new javax.swing.JMenuItem();
        mnBuscarFoto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnAgregarVideo = new javax.swing.JMenuItem();
        mnEliminarVideo = new javax.swing.JMenuItem();
        mnBuscarVideo = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jMenu1.setText("Fotos");

        mnAgregarFoto.setText("Agregar");
        mnAgregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAgregarFotoActionPerformed(evt);
            }
        });
        jMenu1.add(mnAgregarFoto);

        mnEliminarFoto.setText("Eliminar");
        jMenu1.add(mnEliminarFoto);

        mnBuscarFoto.setText("Buscar/Modificar");
        jMenu1.add(mnBuscarFoto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Videos");

        mnAgregarVideo.setText("Agregar");
        jMenu2.add(mnAgregarVideo);

        mnEliminarVideo.setText("Eliminar");
        mnEliminarVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEliminarVideoActionPerformed(evt);
            }
        });
        jMenu2.add(mnEliminarVideo);

        mnBuscarVideo.setText("Buscar/Modificar");
        jMenu2.add(mnBuscarVideo);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnEliminarVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEliminarVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnEliminarVideoActionPerformed

    private void mnAgregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAgregarFotoActionPerformed
        new VentanaAgregarFoto().setVisible(true);
    }//GEN-LAST:event_mnAgregarFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem mnAgregarFoto;
    private javax.swing.JMenuItem mnAgregarVideo;
    private javax.swing.JMenuItem mnBuscarFoto;
    private javax.swing.JMenuItem mnBuscarVideo;
    private javax.swing.JMenuItem mnEliminarFoto;
    private javax.swing.JMenuItem mnEliminarVideo;
    // End of variables declaration//GEN-END:variables
}
